# Generated by Django 5.0.6 on 2024-06-11 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityInfo',
            fields=[
                ('degree', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('borrow_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20)),
                ('book_author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StorageInfo',
            fields=[
                ('storage_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('storage_position', models.CharField(max_length=20)),
                ('storage_cover', models.ImageField(upload_to='cover/')),
                ('storage_publish', models.CharField(max_length=20)),
                ('storage_publish_time', models.DateField()),
                ('storage_state', models.BooleanField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('admin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_email', models.EmailField(max_length=254)),
                ('login_key', models.CharField(max_length=20)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.departmentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('login_key', models.CharField(max_length=20)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.authorityinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.storageinfo')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRelation',
            fields=[
                ('storage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.storageinfo')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('is_overdue', models.BooleanField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.studentinfo')),
            ],
        ),
    ]
