# Generated by Django 5.0.6 on 2024-06-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrelation',
            name='is_overdue',
        ),
    ]
